// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static const String _webApiKey =
      String.fromEnvironment('FIREBASE_WEB_API_KEY');
  static const String _androidApiKey =
      String.fromEnvironment('FIREBASE_ANDROID_API_KEY');
  static const String _iosApiKey =
      String.fromEnvironment('FIREBASE_IOS_API_KEY');

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static String _requiredValue({
    required String key,
    required String value,
  }) {
    if (value.isEmpty) {
      throw StateError('Missing required dart-define value: $key');
    }
    return value;
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: _requiredValue(
      key: 'FIREBASE_WEB_API_KEY',
      value: _webApiKey,
    ),
    appId: '1:967380985108:web:084981eea879c427900e01',
    messagingSenderId: '967380985108',
    projectId: 'tum2-dev-6283d',
    authDomain: 'tum2-dev-6283d.firebaseapp.com',
    storageBucket: 'tum2-dev-6283d.firebasestorage.app',
    measurementId: 'G-JGTE65V6YN',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: _requiredValue(
      key: 'FIREBASE_ANDROID_API_KEY',
      value: _androidApiKey,
    ),
    appId: '1:967380985108:android:cea417d53a357e5d900e01',
    messagingSenderId: '967380985108',
    projectId: 'tum2-dev-6283d',
    storageBucket: 'tum2-dev-6283d.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: _requiredValue(
      key: 'FIREBASE_IOS_API_KEY',
      value: _iosApiKey,
    ),
    appId: '1:967380985108:ios:c35d6bedbafba846900e01',
    messagingSenderId: '967380985108',
    projectId: 'tum2-dev-6283d',
    storageBucket: 'tum2-dev-6283d.firebasestorage.app',
    iosClientId:
        '967380985108-23kfc1rdv5j30faqiecrq3m718ook59r.apps.googleusercontent.com',
    iosBundleId: 'com.example.tum2',
  );
}
