// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_staging.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static const String _webApiKey = String.fromEnvironment(
    'FIREBASE_WEB_API_KEY',
    defaultValue: '',
  );
  static const String _androidApiKey = String.fromEnvironment(
    'FIREBASE_ANDROID_API_KEY',
    defaultValue: '',
  );
  static const String _iosApiKey = String.fromEnvironment(
    'FIREBASE_IOS_API_KEY',
    defaultValue: '',
  );

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      if (_webApiKey.isEmpty) {
        throw StateError(
          'Missing FIREBASE_WEB_API_KEY for staging web build.',
        );
      }
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        if (_androidApiKey.isEmpty) {
          throw StateError(
            'Missing FIREBASE_ANDROID_API_KEY for staging Android build.',
          );
        }
        return android;
      case TargetPlatform.iOS:
        if (_iosApiKey.isEmpty) {
          throw StateError(
            'Missing FIREBASE_IOS_API_KEY for staging iOS build.',
          );
        }
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: _webApiKey,
    appId: '1:227534906025:web:41ca1f2d60d73c58b03fb8',
    messagingSenderId: '227534906025',
    projectId: 'tum2-staging-45c83',
    authDomain: 'tum2-staging-45c83.firebaseapp.com',
    storageBucket: 'tum2-staging-45c83.firebasestorage.app',
    measurementId: 'G-78K8N2VLG9',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: _androidApiKey,
    appId: '1:227534906025:android:b08627eacb109a43b03fb8',
    messagingSenderId: '227534906025',
    projectId: 'tum2-staging-45c83',
    storageBucket: 'tum2-staging-45c83.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: _iosApiKey,
    appId: '1:227534906025:ios:4962e26ecfb9f9b9b03fb8',
    messagingSenderId: '227534906025',
    projectId: 'tum2-staging-45c83',
    storageBucket: 'tum2-staging-45c83.firebasestorage.app',
    iosClientId:
        '227534906025-tvhoa09a7ls2virhiicgbuuqeb6o7b2g.apps.googleusercontent.com',
    iosBundleId: 'com.floki.tum2.staging',
  );
}
