// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static const String _webApiKey = String.fromEnvironment(
    'FIREBASE_WEB_API_KEY',
    defaultValue: '',
  );
  static const String _androidApiKey = String.fromEnvironment(
    'FIREBASE_ANDROID_API_KEY',
    defaultValue: '',
  );
  static const String _iosApiKey = String.fromEnvironment(
    'FIREBASE_IOS_API_KEY',
    defaultValue: '',
  );

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      if (_webApiKey.isEmpty) {
        throw StateError(
          'Missing FIREBASE_WEB_API_KEY for prod web build.',
        );
      }
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        if (_androidApiKey.isEmpty) {
          throw StateError(
            'Missing FIREBASE_ANDROID_API_KEY for prod Android build.',
          );
        }
        return android;
      case TargetPlatform.iOS:
        if (_iosApiKey.isEmpty) {
          throw StateError(
            'Missing FIREBASE_IOS_API_KEY for prod iOS build.',
          );
        }
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: _webApiKey,
    appId: '1:57567901381:web:dadc4aec40273a4e6662ac',
    messagingSenderId: '57567901381',
    projectId: 'tum2-prod-bc9b4',
    authDomain: 'tum2-prod-bc9b4.firebaseapp.com',
    storageBucket: 'tum2-prod-bc9b4.firebasestorage.app',
    measurementId: 'G-25L5MPEV5Q',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: _androidApiKey,
    appId: '1:57567901381:android:c8a51194d128f4c56662ac',
    messagingSenderId: '57567901381',
    projectId: 'tum2-prod-bc9b4',
    storageBucket: 'tum2-prod-bc9b4.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: _iosApiKey,
    appId: '1:57567901381:ios:e07d92eae4e8efca6662ac',
    messagingSenderId: '57567901381',
    projectId: 'tum2-prod-bc9b4',
    storageBucket: 'tum2-prod-bc9b4.firebasestorage.app',
    iosClientId:
        '57567901381-odvgplb0o1a9r0jv1uljdig4gfj1jihp.apps.googleusercontent.com',
    iosBundleId: 'com.floki.tum2',
  );
}
