// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_staging.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByRw816BJKUl7OOHLUDK1hIsyPtwkAtMw',
    appId: '1:227534906025:web:41ca1f2d60d73c58b03fb8',
    messagingSenderId: '227534906025',
    projectId: 'tum2-staging-45c83',
    authDomain: 'tum2-staging-45c83.firebaseapp.com',
    storageBucket: 'tum2-staging-45c83.firebasestorage.app',
    measurementId: 'G-78K8N2VLG9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqk-OvQgqOiC8QSJ5wq-9T9GpeHaoPmvA',
    appId: '1:227534906025:android:b08627eacb109a43b03fb8',
    messagingSenderId: '227534906025',
    projectId: 'tum2-staging-45c83',
    storageBucket: 'tum2-staging-45c83.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnPAba5_P-gSQxh0MJL-0XP4Os9aDL_3E',
    appId: '1:227534906025:ios:4962e26ecfb9f9b9b03fb8',
    messagingSenderId: '227534906025',
    projectId: 'tum2-staging-45c83',
    storageBucket: 'tum2-staging-45c83.firebasestorage.app',
    iosClientId: '227534906025-tvhoa09a7ls2virhiicgbuuqeb6o7b2g.apps.googleusercontent.com',
    iosBundleId: 'com.floki.tum2.staging',
  );
}
