// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJlI8afJYe4rssEjPfCQ9hGZrAl67lOmk',
    appId: '1:57567901381:web:dadc4aec40273a4e6662ac',
    messagingSenderId: '57567901381',
    projectId: 'tum2-prod-bc9b4',
    authDomain: 'tum2-prod-bc9b4.firebaseapp.com',
    storageBucket: 'tum2-prod-bc9b4.firebasestorage.app',
    measurementId: 'G-25L5MPEV5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcxvM2LZUSqIuI_rRL1dM-fb-DK801jRo',
    appId: '1:57567901381:android:8231184d4ce8649b6662ac',
    messagingSenderId: '57567901381',
    projectId: 'tum2-prod-bc9b4',
    storageBucket: 'tum2-prod-bc9b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPaHsOABjld_yiucesSVemAsY9llb4tuU',
    appId: '1:57567901381:ios:e07d92eae4e8efca6662ac',
    messagingSenderId: '57567901381',
    projectId: 'tum2-prod-bc9b4',
    storageBucket: 'tum2-prod-bc9b4.firebasestorage.app',
    iosClientId:
        '57567901381-odvgplb0o1a9r0jv1uljdig4gfj1jihp.apps.googleusercontent.com',
    iosBundleId: 'com.floki.tum2',
  );
}
